name: Kelsey Nihiser
favicon: null
layout_spectrum: 0.7552
typography_spectrum: 0.20419
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e0e32'
    - '#d0a24f'
    - '#a04b2f'
    - '#e4cc82'
    - '#7c2b30'
  brandStrength: 0.25
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
